### ISSUE TITLE
Dear Khoa

### ISSUE THREAD

**Issue by buukhanh243** [khoaa-dev/QuanLyThuVien_KhP2T#1]
Chào bạn, mình có follow kênh của bạn trên youtube, bạn có thể cho mình xin báo cáo bài quản lý thư viện để tham khảo được không ạ! xin cảm ơn bạn rất nhiều
buukhanh243@gmail.com

**Comment by khoaa-dev** [comment]
https://github.com/khoaa-dev/QuanLyThuVien_KhP2T
Mình có source đây chứ không có báo cáo bằng word nha
